### ISSUE TITLE
Implement "My Profiles" flow

### ISSUE THREAD

**Issue by dayotte** [platform-coop-toolkit/coop-map-directory-index#28]
Need a flow from "My Profiles" in homepage nav, dependent on whether or not user has already created a profile, or has multiple profiles.

**Comment by dayotte** [comment]
@erictheise here is the flow I'm imagining, working on mocking up the nav behaviour and "choose from list" page https://files.inclusivedesign.ca/s/QX5c9pqBuu9Wdpb

**Comment by dayotte** [comment]
@erictheise thinking this would work, but wondering if @jhung  could take a look re: accessibliity of using dropdown nav in this way. Individual profile names link to the profile pages directly from the nav, so there is some inconsistency, because "Create new" takes user to profile creation flow. 
https://files.inclusivedesign.ca/s/O0ue9DbPGGyKCtl

**Comment by dayotte** [comment]
Spoke with @jhung and have updated the file, attaching updated mockup here.
![my profiles nav flow](https://user-images.githubusercontent.com/6207009/79907640-c9c73a00-83ce-11ea-8723-12a1e049bc36.png)

**Comment by erictheise** [comment]
Thanks for posting the image here in the issue. It appears to have a transparent background because when I click to enlarge all the arrows disappear against the black modal background.

My opinion is that the distinction between individual profiles, of which a user can have only one, and organizational profiles, of which a user can have many, should be made clearer earlier. This is especially true following the `profile(s) created` where there's no visual distinction made between the two. Looking at that I would think I could create any number of profiles.

One approach might be to alter `My profiles` so that it only gives access to organizational profiles and have the creation/editing function for an individual be linked to their email address which displays after they've logged in. Seems a very common pattern for individual access to `account` (e.g. changing passwords or billing (not relevant here)), `profile`, `likes/favorites`, etc.

**Comment by erictheise** [comment]
![image](https://user-images.githubusercontent.com/317680/79913983-54ad3200-83d9-11ea-9052-f1c2c177ea81.png)

**Comment by dayotte** [comment]
@erictheise I think it might be confusing to have profiles living in different places, I've updated the mockups to keep them all under My Profiles but to make the distinction clearer.
![My Profiles nav MVP](https://user-images.githubusercontent.com/6207009/80144055-b056f700-8562-11ea-8290-e6c173b92488.png)

**Comment by erictheise** [comment]
Thanks @dayotte.

Question for you, @greatislander, or @jhung: what are the correct Pinecone classes to apply to the user's email address as shown in the directory screenshot two comments above? I tried simply replacing the anchor tag with a span, which keeps the correct color and vertical-alignment, but as a `menu__item` it still responds to mouseover by inverting colors.

It is no longer a menu item. It is just a confirmation of logged in status/identity.

**Comment by erictheise** [comment]
@greatislander, this bad boy needs some styling. Don't know if these should be core to Pinecone or unique to Directory but there's definitely a gap between live and wireframe.

![image](https://user-images.githubusercontent.com/317680/80177845-b1fbdb80-85b1-11ea-8b3e-51b853e431c0.png)

**Comment by dayotte** [comment]
@erictheise @greatislander I recommend using the same font style, size and colours as in the nav for the resource library, with the addition of bold font for the headers, the underlined links to profiles and let's use dark mint #203131 for the calls to action. Do you need more details from me?

**Comment by erictheise** [comment]
@greatislander, also need margin/border/padding specs for `menu__submenu` in an application like this as well as a spec on the thickness of the `divider`.

**Comment by erictheise** [comment]
@greatislander, as mentioned in iteration planning today the [new version of the nav bar](https://github.com/platform-coop-toolkit/coop-map-directory-index/issues/31) dropped the display of the logged in user's email address so the [request for a class that looks like a menu item but is only a display of state](https://github.com/platform-coop-toolkit/coop-map-directory-index/issues/28#issuecomment-618660461) can be ignored. Sorry for the noise.

**Comment by erictheise** [comment]
This issue essentially blocked by lack of [organization profile flow](https://github.com/platform-coop-toolkit/coop-map-directory-index/issues/6).
