### ISSUE TITLE
Finalize list of survey/profile Challenges and mapping from previous Pressures

### ISSUE THREAD

**Issue by erictheise** [platform-coop-toolkit/coop-map-directory-index#32]
61 respondents to Trebor's _Survey of the International Cooperative Digital Ecosystem 2020_ selected one of the following values for the question

__10) What challenges are you facing with your project or enterprise?__

```
Pressure to imitate mainstream groups (e.g., “best practices”)
Pressure to follow ethics or customs (e.g., internal hierarchy)
Pressure to find funding in order to motivate cooperators and developers.
Pressure to comply with regulations (e.g., accounting standards)
Pressure to compete for market share (e.g., sales, revenue, funding)
Pressure to adopt professional standards (e.g., training or hiring)
Governance and participation
```

@dayotte has been creating new _challenges_ as part of the [Organizational Profile creation flow](https://github.com/platform-coop-toolkit/coop-map-directory-index/issues/6). Following from today's Zoom meeting about the survey the action items are

1. collect unique responses from the intervening ~150 respondents. @difea451, could you extract those from the Google sheet and post them here?
2. finalize the list of _challenges_ to be presented in the survey and in Profile creation. (@dayotte)
3. provide a mapping of existing _challenges_ (those above and any new ones coming from @difea451) to the newly worded ones and account for any inexact matches. (@dayotte)
4. provide presentation order of the _challenges_. (@dayotte)
4. update the database to replace the existing "Pressure to…" responses with the new challenges. (@erictheise)

This blocks survey deployment using `platform.coop` systems and delays integration of incoming survey data with directory data.

**Comment by dayotte** [comment]
@erictheise here you go https://docs.google.com/spreadsheets/d/1-KReYM4F0FX7NZdTLlcNRo-ZmNfiPmZ0IBmMq8hmNYc/edit?usp=sharing

**Comment by erictheise** [comment]
```
Pressure to adopt professional standards (e.g., training or hiring)
  -> Adopting professional business standards

Pressure to compete for market share (e.g., sales, revenue, funding)
  -> Competing for market share

Pressure to comply with regulations (e.g., accounting standards)
  -> Complying with regulations

Pressure to imitate mainstream groups (e.g., “best practices”)
  -> Developing co-operative best practices

Pressure to follow ethics or customs (e.g., internal hierarchy)
  -> Developing co-operative culture

Pressure to find funding in order to motivate cooperators and developers
  -> Finding funding

Governance and participation
  -> Governance and participation

Other (describe) 
  -> Other (describe)
```

Going to wait a bit for survey responses from @difea451 to see if there are any "popular" pressures we haven't considered. Thanks for the quick turnaround.

**Comment by erictheise** [comment]
P.S. @dayotte "Governance" is misspelled in the __Short form directory tags__ column but I don't have permission to correct it.

**Comment by dayotte** [comment]
@greatislander confirming the list of challenges (and mappings) to go forward with:

Pressure to adopt professional standards (e.g., training or hiring)
  -> Adopting professional business standards
Pressure to compete for market share (e.g., sales, revenue, funding)
  -> Competing for market share
Pressure to comply with regulations (e.g., accounting standards)
  -> Complying with regulations
Pressure to imitate mainstream groups (e.g., “best practices”)
  -> Developing co-operative best practices
Pressure to follow ethics or customs (e.g., internal hierarchy)
  -> Developing co-operative culture
Pressure to find funding in order to motivate cooperators and developers
  -> Finding funding
Governance and participation
  -> Governance and participation
Other (describe) 
  -> Other (describe)

**Comment by greatislander** [comment]
Updated in production database.
