### ISSUE TITLE
Finalize map design parameters 

### ISSUE THREAD

**Issue by dayotte** [platform-coop-toolkit/coop-map-directory-index#71]
Need to finalize the map design parameters including max/min/default zoom, zoom step size, light/dark cartography, contrast for type accessibility.

None of the “Light”, “Dark” and “Streets” options in [Mapbox](https://www.mapbox.com/maps?exp1=B&utm_expid=.QH0y23voThauLhQxXrGdfQ.1&utm_referrer=https%3A%2F%2Fwww.mapbox.com%2F) appear to have good type/background contrast so customizing the colours to ensure good contrast is likely necessary.

WebAIM contrast checker: [https://webaim.org/resources/contrastchecker/](url)

FYI @cherylhjli, @greatislander 

See attached screenshots and style sheet (coming soon):
- [x] implement updated map colours
- [x] implement updated map typography
- [x] implement updated map label density

**Comment by cherylhjli** [comment]
Visual design specs are here:
https://www.figma.com/proto/tXFtpKPWuGUFrotFsXshZq/Directory-Wireframes_DA?node-id=1742%3A7&viewport=542%2C515%2C0.11305409669876099&scaling=min-zoom

If it helps at all, here's the original map I was playing with in customizing colours and type. I know we're not using mapbox, I was just using it for a quick way to customize visuals.
https://api.mapbox.com/styles/v1/cherylhjli/ckb6pxs8341uc1iqty75bfpuq.html?fresh=true&title=copy&access_token=pk.eyJ1IjoiY2hlcnlsaGpsaSIsImEiOiJja2I2bGpjdXcxN2t5MndueGE2NzAxMTU3In0.5hkjGApeV4_pI6JFbgSFLQ

**Comment by dayotte** [comment]
thanks @cherylhjli !

**Comment by erictheise** [comment]
I cannot persuade the build tools to do what I'd like @greatislander so I've committed some pseudocode. Probably you can modify it in no time.

There are really two things at play here.

To edit a map style the `glyphs` and `sprites` urls need to be hardcoded, and they do need to be swapped out in production to match what's in the `.env` file. It would also be helpful to be able to switch between alternative styles based on a value in the `.env` file.

So the idea is to use `laravel-mix-string-replace` to swap out domain and port, and to swap out the style name, in the course of promoting the active `style.json` to what you've implemented as `mapStyle.js`. I've left some illustrative regexps in the `.stringReplace` block but have been unable to get simple string replacements to work in the `.copy` block.

[laravel-mix-string-replace](https://github.com/kaldor/laravel-mix-string-replace)
[string-replace-loader](https://github.com/Va1/string-replace-loader)

Again, I imagine you can get this working in a snap, or propose another way to accomplish this.

**Comment by cherylhjli** [comment]
On mobile, when the map stretches past the breakpoint on a device, a user will have trouble with scrolling past the map without scrolling through the map first since they use the same gesture (one-finger scroll). While the margins at the side act as a way for the user to scroll past the map, it may be difficult for someone with bigger fingers or mobility issues. Asking the user to scroll through the map to scroll past it may move them out of their place, and change the results below. 

Hoping to see if there's a way to change the gesture used to scroll in the map - a common way to get around this is using a two-finger scroll on mobile for the map, with one-finger for scrolling through the page.
Example (view on mobile) - https://www.nofrills.ca/store-locator 

Changing the height of the map is also another option, but it may limit how useful the map is on mobile.
Example (view on mobile) - https://stores.telus.com/
(disregard the parallax behaviour)

**Comment by cherylhjli** [comment]
Specs for map cluster & group colours:
![Screen Shot 2020-08-10 at 11 17 33 AM](https://user-images.githubusercontent.com/9353905/89799213-245de080-dafb-11ea-93bf-8ebf86ee7301.png)

I ran them through a colour blindness simulator - while not perfect, I think there is some distinction between all of them

**Comment by cherylhjli** [comment]
@greatislander - Updated with individual cluster colours. Unfortunately there was no red darker than red 500 so I added a new colour - let me know if that becomes an issue, we can revisit.
